name: CI

on:
  push:
    branches:
      - 'main-echoes'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PHP rename utils
        uses: actions/checkout@master
        with:
          repository: elaskavaia/bga-sharedcode
          token: ${{ secrets.GITHUB_TOKEN }}
          path: './bga-sharedcode'
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          path: './innovation'
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.1:'
      - name: Rename innovation to innovationdev
        run: php bga-sharedcode/misc/bgaprojectrename.php innovation innovationdev
      - name: Delete files that we do not want to upload
        run: cd innovationdev && rm -rf .vscode .git .github .DS_Store misc node_modules package-lock.json vendor composer.json composer.lock phpunit.xml tests && cd ..
      - name: Push to BGA
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
         username: ${{ secrets.BGA_USERNAME }}
         server: '1.studio.boardgamearena.com'
         password: ${{ secrets.BGA_PASSWORD }} 
         local_path: './innovationdev'
         remote_path: '.'
         sftp_only: true
